// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_to_team.sql

package database

import (
	"context"
)

const addPokemonToTeam = `-- name: AddPokemonToTeam :exec
INSERT INTO teams(id, created_at, updated_at, user_name, poke)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
`

type AddPokemonToTeamParams struct {
	UserName string
	Poke     string
}

func (q *Queries) AddPokemonToTeam(ctx context.Context, arg AddPokemonToTeamParams) error {
	_, err := q.db.ExecContext(ctx, addPokemonToTeam, arg.UserName, arg.Poke)
	return err
}
