// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_pokemon.sql

package database

import (
	"context"
)

const addPokemon = `-- name: AddPokemon :exec
INSERT INTO pokemon(id, name, sprite, type, url, base_xp)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type AddPokemonParams struct {
	ID     int32
	Name   string
	Sprite string
	Type   string
	Url    string
	BaseXp int32
}

func (q *Queries) AddPokemon(ctx context.Context, arg AddPokemonParams) error {
	_, err := q.db.ExecContext(ctx, addPokemon,
		arg.ID,
		arg.Name,
		arg.Sprite,
		arg.Type,
		arg.Url,
		arg.BaseXp,
	)
	return err
}
