// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_team.sql

package database

import (
	"context"
)

const getTeam = `-- name: GetTeam :many
SELECT user_name, created_at, updated_at, poke, count FROM teams
WHERE user_name = $1
`

func (q *Queries) GetTeam(ctx context.Context, userName string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeam, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.UserName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Poke,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
