// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_pokemon_by_name.sql

package database

import (
	"context"
)

const getPokeByName = `-- name: GetPokeByName :one
SELECT id, name, sprite, type, url FROM pokemon
WHERE name = $1
`

func (q *Queries) GetPokeByName(ctx context.Context, name string) (Pokemon, error) {
	row := q.db.QueryRowContext(ctx, getPokeByName, name)
	var i Pokemon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sprite,
		&i.Type,
		&i.Url,
	)
	return i, err
}
