// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_pokemon_by_id.sql

package database

import (
	"context"
)

const getPokeByID = `-- name: GetPokeByID :one
SELECT id, name, sprite, type, url, base_xp FROM pokemon
WHERE id = $1
`

func (q *Queries) GetPokeByID(ctx context.Context, id int32) (Pokemon, error) {
	row := q.db.QueryRowContext(ctx, getPokeByID, id)
	var i Pokemon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sprite,
		&i.Type,
		&i.Url,
		&i.BaseXp,
	)
	return i, err
}
