// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Pokemon struct {
	ID     int32
	Name   string
	Sprite string
	Type   string
	Url    string
	BaseXp int32
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserName  string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Team struct {
	UserName  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Poke      string
	Count     int32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserName  string
	PassHash  string
}
