// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: new_refresh.sql

package database

import (
	"context"
	"time"
)

const insertRefresh = `-- name: InsertRefresh :exec
INSERT INTO refresh_tokens(token, created_at, updated_at, user_name, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
`

type InsertRefreshParams struct {
	Token     string
	UserName  string
	ExpiresAt time.Time
}

func (q *Queries) InsertRefresh(ctx context.Context, arg InsertRefreshParams) error {
	_, err := q.db.ExecContext(ctx, insertRefresh, arg.Token, arg.UserName, arg.ExpiresAt)
	return err
}
