// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: poke_count.sql

package database

import (
	"context"
)

const numPokemon = `-- name: NumPokemon :one
SELECT COUNT(*)
FROM pokemon
`

func (q *Queries) NumPokemon(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, numPokemon)
	var count int64
	err := row.Scan(&count)
	return count, err
}
