// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_pokemon.sql

package database

import (
	"context"
)

const resetPokemon = `-- name: ResetPokemon :exec
TRUNCATE TABLE pokemon CASCADE
`

func (q *Queries) ResetPokemon(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPokemon)
	return err
}
