// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_teams.sql

package database

import (
	"context"
)

const resetTeams = `-- name: ResetTeams :exec
TRUNCATE TABLE teams
`

func (q *Queries) ResetTeams(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetTeams)
	return err
}
