// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_user_teams.sql

package database

import (
	"context"
)

const resetUserTeam = `-- name: ResetUserTeam :exec
DELETE FROM teams
WHERE user_name = $1
`

func (q *Queries) ResetUserTeam(ctx context.Context, userName string) error {
	_, err := q.db.ExecContext(ctx, resetUserTeam, userName)
	return err
}
