// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: validate_pokemon.sql

package database

import (
	"context"
)

const validatePokemon = `-- name: ValidatePokemon :one
SELECT COUNT(*) 
FROM pokemon 
WHERE name = $1
`

func (q *Queries) ValidatePokemon(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, validatePokemon, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
